# Use Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Install necessary dependencies and cleanup in one step
RUN apt-get update \
&& apt-get install -y curl iproute2 sshfs unzip less groff \
&& curl -LO https://dl.k8s.io/release/v1.23.6/bin/linux/amd64/kubectl \
&& chmod +x kubectl \
&& mv kubectl /usr/local/bin/ \
&& curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
&& unzip awscliv2.zip \
&& ./aws/install \
&& rm -rf awscliv2.zip aws \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

# Add the above tools to the PATH
ENV PATH="/usr/local/bin:${PATH}"
