# Use Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Install necessary dependencies, including SSL certificates
RUN apt-get update && apt-get install -y --no-install-recommends \
ca-certificates \
&& apt-get clean && rm -rf /var/lib/apt/lists/*

# Install other required dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
curl iproute2 sshfs unzip less groff \
&& apt-get clean && rm -rf /var/lib/apt/lists/*

# Install kubectl
RUN curl -LO https://dl.k8s.io/release/v1.23.6/bin/linux/amd64/kubectl \
&& chmod +x kubectl \
&& mv kubectl /usr/local/bin/

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
&& unzip awscliv2.zip \
&& ./aws/install \
&& rm -rf awscliv2.zip aws

# Add the above tools to the PATH
ENV PATH="/usr/local/bin:${PATH}"

# Create the appuser with a specific UID and GID (e.g., 1001)
RUN groupadd -r appgroup -g 1001 && useradd -u 1001 -r -g appgroup appuser

USER appuser
